version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    command: >
      sh -c "
      python -m venv venv &&
      . venv/bin/activate &&
      pip install -r requirements.txt &&
      gunicorn --bind 0.0.0.0:8000 wsgi:app"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
